<?php

/**
 * CourseRegistrationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CourseRegistrationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CourseRegistrationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CourseRegistration');
    }
}