<?php

/**
 * LessonPlanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LessonPlanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LessonPlanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LessonPlan');
    }
}