<?php

/**
 * RegistrationStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegistrationStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegistrationStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RegistrationStatus');
    }
}