<?php

/**
 * BaseFeedback
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $question
 * @property integer $videochat
 * @property integer $website
 * @property integer $questionability
 * @property integer $interest
 * @property Question $Question
 * @property Answer $Answer
 * 
 * @method integer  getId()              Returns the current record's "id" value
 * @method integer  getQuestion()        Returns the current record's "question" value
 * @method integer  getVideochat()       Returns the current record's "videochat" value
 * @method integer  getWebsite()         Returns the current record's "website" value
 * @method integer  getQuestionability() Returns the current record's "questionability" value
 * @method integer  getInterest()        Returns the current record's "interest" value
 * @method Question getQuestion()        Returns the current record's "Question" value
 * @method Answer   getAnswer()          Returns the current record's "Answer" value
 * @method Feedback setId()              Sets the current record's "id" value
 * @method Feedback setQuestion()        Sets the current record's "question" value
 * @method Feedback setVideochat()       Sets the current record's "videochat" value
 * @method Feedback setWebsite()         Sets the current record's "website" value
 * @method Feedback setQuestionability() Sets the current record's "questionability" value
 * @method Feedback setInterest()        Sets the current record's "interest" value
 * @method Feedback setQuestion()        Sets the current record's "Question" value
 * @method Feedback setAnswer()          Sets the current record's "Answer" value
 * 
 * @package    virtualmentor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFeedback extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('feedback');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('question', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('videochat', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('website', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('questionability', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('interest', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Question', array(
             'local' => 'question',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Answer', array(
             'local' => 'id',
             'foreign' => 'feedback'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}