<?php

/**
 * BaseRegistrationStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $name
 * @property Doctrine_Collection $StudentsStatuses
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method varchar             getName()             Returns the current record's "name" value
 * @method Doctrine_Collection getStudentsStatuses() Returns the current record's "StudentsStatuses" collection
 * @method RegistrationStatus  setId()               Sets the current record's "id" value
 * @method RegistrationStatus  setName()             Sets the current record's "name" value
 * @method RegistrationStatus  setStudentsStatuses() Sets the current record's "StudentsStatuses" collection
 * 
 * @package    virtualmentor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegistrationStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('registration_status');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CourseRegistration as StudentsStatuses', array(
             'local' => 'id',
             'foreign' => 'status'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}