<?php

/**
 * BaseLessonPlan
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $name
 * @property string $description
 * @property integer $durationindays
 * @property integer $owner
 * @property integer $course
 * @property Member $Member
 * @property Course $Course
 * @property Doctrine_Collection $Questions
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method varchar             getName()           Returns the current record's "name" value
 * @method string              getDescription()    Returns the current record's "description" value
 * @method integer             getDurationindays() Returns the current record's "durationindays" value
 * @method integer             getOwner()          Returns the current record's "owner" value
 * @method integer             getCourse()         Returns the current record's "course" value
 * @method Member              getMember()         Returns the current record's "Member" value
 * @method Course              getCourse()         Returns the current record's "Course" value
 * @method Doctrine_Collection getQuestions()      Returns the current record's "Questions" collection
 * @method LessonPlan          setId()             Sets the current record's "id" value
 * @method LessonPlan          setName()           Sets the current record's "name" value
 * @method LessonPlan          setDescription()    Sets the current record's "description" value
 * @method LessonPlan          setDurationindays() Sets the current record's "durationindays" value
 * @method LessonPlan          setOwner()          Sets the current record's "owner" value
 * @method LessonPlan          setCourse()         Sets the current record's "course" value
 * @method LessonPlan          setMember()         Sets the current record's "Member" value
 * @method LessonPlan          setCourse()         Sets the current record's "Course" value
 * @method LessonPlan          setQuestions()      Sets the current record's "Questions" collection
 * 
 * @package    virtualmentor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLessonPlan extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lesson_plan');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('durationindays', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('owner', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('course', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Member', array(
             'local' => 'owner',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Course', array(
             'local' => 'course',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('Question as Questions', array(
             'local' => 'id',
             'foreign' => 'lessonplan'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}