<?php

/**
 * BaseCourse
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $name
 * @property string $description
 * @property integer $owner
 * @property Member $Member
 * @property Doctrine_Collection $Lessons
 * @property Doctrine_Collection $Registrations
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method varchar             getName()          Returns the current record's "name" value
 * @method string              getDescription()   Returns the current record's "description" value
 * @method integer             getOwner()         Returns the current record's "owner" value
 * @method Member              getMember()        Returns the current record's "Member" value
 * @method Doctrine_Collection getLessons()       Returns the current record's "Lessons" collection
 * @method Doctrine_Collection getRegistrations() Returns the current record's "Registrations" collection
 * @method Course              setId()            Sets the current record's "id" value
 * @method Course              setName()          Sets the current record's "name" value
 * @method Course              setDescription()   Sets the current record's "description" value
 * @method Course              setOwner()         Sets the current record's "owner" value
 * @method Course              setMember()        Sets the current record's "Member" value
 * @method Course              setLessons()       Sets the current record's "Lessons" collection
 * @method Course              setRegistrations() Sets the current record's "Registrations" collection
 * 
 * @package    virtualmentor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCourse extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('course');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('owner', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Member', array(
             'local' => 'owner',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('LessonPlan as Lessons', array(
             'local' => 'id',
             'foreign' => 'course'));

        $this->hasMany('CourseRegistration as Registrations', array(
             'local' => 'id',
             'foreign' => 'course'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}