<?php

/**
 * BaseQuestion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $lessonplan
 * @property varchar $name
 * @property string $question
 * @property LessonPlan $LessonPlan
 * @property Feedback $Feedback
 * @property Doctrine_Collection $Answers
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method integer             getLessonplan() Returns the current record's "lessonplan" value
 * @method varchar             getName()       Returns the current record's "name" value
 * @method string              getQuestion()   Returns the current record's "question" value
 * @method LessonPlan          getLessonPlan() Returns the current record's "LessonPlan" value
 * @method Feedback            getFeedback()   Returns the current record's "Feedback" value
 * @method Doctrine_Collection getAnswers()    Returns the current record's "Answers" collection
 * @method Question            setId()         Sets the current record's "id" value
 * @method Question            setLessonplan() Sets the current record's "lessonplan" value
 * @method Question            setName()       Sets the current record's "name" value
 * @method Question            setQuestion()   Sets the current record's "question" value
 * @method Question            setLessonPlan() Sets the current record's "LessonPlan" value
 * @method Question            setFeedback()   Sets the current record's "Feedback" value
 * @method Question            setAnswers()    Sets the current record's "Answers" collection
 * 
 * @package    virtualmentor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuestion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('question');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('lessonplan', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('question', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('LessonPlan', array(
             'local' => 'lessonplan',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Feedback', array(
             'local' => 'id',
             'foreign' => 'question'));

        $this->hasMany('Answer as Answers', array(
             'local' => 'id',
             'foreign' => 'question'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}