<?php

/**
 * BaseAnswer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $mentee
 * @property integer $question
 * @property integer $feedback
 * @property string $answer
 * @property Member $Member
 * @property Question $Question
 * @property Feedback $Feedback
 * 
 * @method integer  getId()       Returns the current record's "id" value
 * @method integer  getMentee()   Returns the current record's "mentee" value
 * @method integer  getQuestion() Returns the current record's "question" value
 * @method integer  getFeedback() Returns the current record's "feedback" value
 * @method string   getAnswer()   Returns the current record's "answer" value
 * @method Member   getMember()   Returns the current record's "Member" value
 * @method Question getQuestion() Returns the current record's "Question" value
 * @method Feedback getFeedback() Returns the current record's "Feedback" value
 * @method Answer   setId()       Sets the current record's "id" value
 * @method Answer   setMentee()   Sets the current record's "mentee" value
 * @method Answer   setQuestion() Sets the current record's "question" value
 * @method Answer   setFeedback() Sets the current record's "feedback" value
 * @method Answer   setAnswer()   Sets the current record's "answer" value
 * @method Answer   setMember()   Sets the current record's "Member" value
 * @method Answer   setQuestion() Sets the current record's "Question" value
 * @method Answer   setFeedback() Sets the current record's "Feedback" value
 * 
 * @package    virtualmentor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnswer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('answer');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('mentee', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('question', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('feedback', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('answer', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Member', array(
             'local' => 'mentee',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Question', array(
             'local' => 'question',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Feedback', array(
             'local' => 'feedback',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}