<?php

/**
 * BaseMember
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $firstname
 * @property varchar $lastname
 * @property varchar $email
 * @property varchar $password
 * @property integer $membership
 * @property Membership $Membership
 * @property Doctrine_Collection $Courses
 * @property Doctrine_Collection $LessonPlans
 * @property Doctrine_Collection $Answers
 * @property Doctrine_Collection $CourseRegistrations
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method varchar             getFirstname()           Returns the current record's "firstname" value
 * @method varchar             getLastname()            Returns the current record's "lastname" value
 * @method varchar             getEmail()               Returns the current record's "email" value
 * @method varchar             getPassword()            Returns the current record's "password" value
 * @method integer             getMembership()          Returns the current record's "membership" value
 * @method Membership          getMembership()          Returns the current record's "Membership" value
 * @method Doctrine_Collection getCourses()             Returns the current record's "Courses" collection
 * @method Doctrine_Collection getLessonPlans()         Returns the current record's "LessonPlans" collection
 * @method Doctrine_Collection getAnswers()             Returns the current record's "Answers" collection
 * @method Doctrine_Collection getCourseRegistrations() Returns the current record's "CourseRegistrations" collection
 * @method Member              setId()                  Sets the current record's "id" value
 * @method Member              setFirstname()           Sets the current record's "firstname" value
 * @method Member              setLastname()            Sets the current record's "lastname" value
 * @method Member              setEmail()               Sets the current record's "email" value
 * @method Member              setPassword()            Sets the current record's "password" value
 * @method Member              setMembership()          Sets the current record's "membership" value
 * @method Member              setMembership()          Sets the current record's "Membership" value
 * @method Member              setCourses()             Sets the current record's "Courses" collection
 * @method Member              setLessonPlans()         Sets the current record's "LessonPlans" collection
 * @method Member              setAnswers()             Sets the current record's "Answers" collection
 * @method Member              setCourseRegistrations() Sets the current record's "CourseRegistrations" collection
 * 
 * @package    virtualmentor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMember extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('member');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('firstname', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('lastname', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('password', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('membership', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Membership', array(
             'local' => 'membership',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('Course as Courses', array(
             'local' => 'id',
             'foreign' => 'owner'));

        $this->hasMany('LessonPlan as LessonPlans', array(
             'local' => 'id',
             'foreign' => 'owner'));

        $this->hasMany('Answer as Answers', array(
             'local' => 'id',
             'foreign' => 'mentee'));

        $this->hasMany('CourseRegistration as CourseRegistrations', array(
             'local' => 'id',
             'foreign' => 'mentee'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}