<?php

/**
 * BaseMembership
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property varchar $name
 * @property Doctrine_Collection $Members
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method varchar             getName()    Returns the current record's "name" value
 * @method Doctrine_Collection getMembers() Returns the current record's "Members" collection
 * @method Membership          setId()      Sets the current record's "id" value
 * @method Membership          setName()    Sets the current record's "name" value
 * @method Membership          setMembers() Sets the current record's "Members" collection
 * 
 * @package    virtualmentor
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMembership extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('membership');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Member as Members', array(
             'local' => 'id',
             'foreign' => 'membership'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}